In [92]:
import pandas as pd
import pickle
file_path = 'encoded_brand_dict.pkl'
file_path2 = 'encoded_OS_dict.pkl   '
# Load the dictionary from the file
with open(file_path, 'rb') as file:
    encoded_brand_dict = pickle.load(file)
print(encoded_brand_dict)
with open(file_path2, 'rb') as file:
    encoded_OS_dict = pickle.load(file)
print(encoded_OS_dict)

{'dell': 13, 'asus': 5, 'msi': 33, 'acer': 0, 'lenovo': 29, 'hp': 23, 'lg': 30, 'samsung': 39, 'razer': 37, 'best notebooks': 8, 'rokc': 38, 'microsoft': 32, 'gigabyte': 19, 'ea': 15, 'ist computers': 26, 'apple': 4, 'best 2 in 1 laptop': 7, 'yoga notebook': 56, 'bintec': 9, 'gateway': 18, 'dynabook': 14, 'travelmate': 53, 'intel': 25, 'techdeal': 45, 'toshiba': 52, 'topseller': 51, 'onn': 34, 'elitebook': 16, 'panasonic': 35, 'fusion5': 17, 'hunsn': 24, 'goldengulf': 20, 'amd': 3, 'smart buy probook': 42, 'precision': 36, 'hewlett-packard': 22, 'thunderb': 48, 'thinkpad': 46, 'aichiw': 1, 'xammue': 55, 'ctl': 12, 'smart buy elitebook': 41, 'core innovations': 11, 'bmax': 10, 'gpdbrandstore': 21, 'luqeeg': 31, 'awow': 6, nan: 57, 'latitude': 28, 'tmp': 49, 'srfc': 43, 'weeliao': 54, 'tocosy': 50, 'surface': 44, 'thomson': 47, 'alienware': 2, 'iview': 27, 'sgin': 40}
{'Windows 10': 10, 'Windows 11': 13, 'Windows 8.1': 17, 'No OS': 5, 'Windows Pro': 18, 'Ubuntu Linux 18.04': 7, 'Windows 7': 15, 'ChromeOS': 1, 'Windows 8': 16, 'Chrome OS': 0, 'MacOS': 4, 'Ubuntu Linux 20.04': 8, 'Google Chrome': 2, 'Windows 1111': 14, 'Linux': 3, 'Windows 108': 12, 'Windows 1012': 11, 'Windows Vista': 19, 'Windows 1': 9, 'OS X 10.10 Yosemite': 6}

In [93]:
data=pd.read_csv('new_test.csv')
data.drop(columns=['CPU Name','GPU Name'],axis=1,inplace=True)
data['Brand'] = data['Brand'].str.lower()
data

,Brand,CPU Mark,GPU Mark,Monitor,Width,Height,RAM,Storage Amount,OS,Weight,Price
0,dell,17546,2690,14.0,1920,1080,16,512.0,Windows 10,0.97,1292.39
1,hp,13481,2690,14.0,1920,1200,32,2048.0,Windows 10,2.22,1049.00
2,asus,2003,1476,14.0,1920,1080,8,64.0,Chrome OS,2.05,446.92
3,dell,23276,1476,14.0,1920,1080,16,256.0,Windows 11,1.38,692.99
4,dell,23276,4253,17.3,1600,900,8,256.0,Windows 10,2.44,1845.80
...,...,...,...,...,...,...,...,...,...,...,...
565,dell,9891,2690,14.0,1920,1080,16,512.0,Windows 10,2.22,749.99
566,dell,15451,2690,14.0,2560,1600,32,512.0,Windows 11,3.64,1950.00
567,dell,2003,1476,11.6,1366,768,8,32.0,Chrome OS,2.11,439.99
568,dell,9891,2690,15.6,1920,1080,32,1024.0,Windows 11,1.77,629.79
569,hp,7460,1476,15.6,1920,1080,16,512.0,Windows 10,2.22,699.99

In [94]:
data['Encoded_Brand'] = data['Brand'].apply(lambda x: encoded_brand_dict.get(x) if x in encoded_brand_dict else None)
data.drop(columns=['Brand'],axis=1,inplace=True)
data['Encoded_OS'] = data['OS'].apply(lambda x: encoded_OS_dict.get(x) if x in encoded_OS_dict else None)
data.drop(columns=['OS'],axis=1,inplace=True)
data['Resolution'] = data['Width']*data['Height']
data.drop(columns=['Width','Height'],axis=1,inplace=True)
data

,CPU Mark,GPU Mark,Monitor,RAM,Storage Amount,Weight,Price,Encoded_Brand,Encoded_OS,Resolution
0,17546,2690,14.0,16,512.0,0.97,1292.39,13,10,2073600
1,13481,2690,14.0,32,2048.0,2.22,1049.00,23,10,2304000
2,2003,1476,14.0,8,64.0,2.05,446.92,5,0,2073600
3,23276,1476,14.0,16,256.0,1.38,692.99,13,13,2073600
4,23276,4253,17.3,8,256.0,2.44,1845.80,13,10,1440000
...,...,...,...,...,...,...,...,...,...,...
565,9891,2690,14.0,16,512.0,2.22,749.99,13,10,2073600
566,15451,2690,14.0,32,512.0,3.64,1950.00,13,13,4096000
567,2003,1476,11.6,8,32.0,2.11,439.99,13,0,1049088
568,9891,2690,15.6,32,1024.0,1.77,629.79,13,13,2073600
569,7460,1476,15.6,16,512.0,2.22,699.99,23,10,2073600

In [95]:
data.to_csv('new_preprocess.csv')